# Generated by Django 5.1.5 on 2026-07-21 20:55

import apps.core.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(db_index=True)),
                ('fecha_hora_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada'), ('no_asistio', 'No asistio')], db_index=True, default='pendiente', max_length=20)),
                ('motivo_consulta', models.TextField()),
                ('notas_doctor', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_hora_inicio'],
                'abstract': False,
            },
        ),
    ]
