# Generated by Django 5.1.5 on 2026-07-21 20:55

import apps.citas.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('doctores', '0001_initial'),
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='doctores.doctorperfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='pacientes.pacienteperfil'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['doctor', 'fecha_hora_inicio'], name='idx_citas_doctor_fecha'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['paciente', '-fecha_hora_inicio'], name='idx_citas_paciente'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado', 'fecha_hora_inicio'], name='idx_citas_estado_fecha'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hora_fin__gt', models.F('fecha_hora_inicio'))), name='cita_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), fields=('doctor', 'fecha_hora_inicio'), name='uq_doctor_horario'),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('estado', 'cancelada'), _negated=True), expressions=[('doctor', '='), (apps.citas.models.RangoCita('fecha_hora_inicio', 'fecha_hora_fin'), '&&')], name='no_solapamiento_citas'),
        ),
    ]
