# Generated by Django 5.1.5 on 2026-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('cita_creada', 'Cita creada'), ('cita_confirmada', 'Cita confirmada'), ('cita_cancelada', 'Cita cancelada'), ('cita_reprogramada', 'Cita reprogramada'), ('recordatorio', 'Recordatorio'), ('sistema', 'Sistema')], default='sistema', max_length=30)),
                ('leido', models.BooleanField(db_index=True, default=False)),
                ('url_destino', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('email', 'Correo electronico'), ('sms', 'SMS'), ('push', 'Push')], default='email', max_length=20)),
                ('fecha_envio_programada', models.DateTimeField(db_index=True)),
                ('enviado', models.BooleanField(db_index=True, default=False)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorios',
                'ordering': ['fecha_envio_programada'],
                'abstract': False,
            },
        ),
    ]
