# Generated by Django 5.1.5 on 2026-07-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_initial'),
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='citas.cita'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leido', '-created_at'], name='idx_notif_usuario_leido'),
        ),
        migrations.AddConstraint(
            model_name='recordatorio',
            constraint=models.UniqueConstraint(fields=('cita', 'tipo', 'fecha_envio_programada'), name='uq_recordatorio_cita_canal_fecha'),
        ),
    ]
