# Generated by Django 5.1.5 on 2026-07-21 20:55

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro'), ('no_especifica', 'Prefiere no decirlo')], max_length=20)),
                ('direccion', apps.core.fields.CharCifradoField(blank=True, default='', max_length=512)),
                ('contacto_emergencia', apps.core.fields.CharCifradoField(blank=True, default='', max_length=512)),
                ('numero_seguro', apps.core.fields.CharCifradoField(blank=True, default='', max_length=512)),
            ],
            options={
                'verbose_name': 'Perfil de paciente',
                'verbose_name_plural': 'Perfiles de pacientes',
                'db_table': 'pacientes_perfil',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
