# Generated by Django 5.1.5 on 2026-07-21 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Bloqueo de horario',
                'verbose_name_plural': 'Bloqueos de horario',
                'db_table': 'bloqueo_horario',
                'ordering': ['-fecha_inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disponibilidad horaria',
                'verbose_name_plural': 'Disponibilidades horarias',
                'db_table': 'disponibilidad_horaria',
                'ordering': ['dia_semana', 'hora_inicio'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numero_licencia', models.CharField(max_length=60, unique=True)),
                ('duracion_consulta_default', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(180)])),
                ('biografia', models.TextField(blank=True)),
                ('tarifa_consulta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Perfil de doctor',
                'verbose_name_plural': 'Perfiles de doctores',
                'db_table': 'doctores_perfil',
                'ordering': ['usuario__first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'db_table': 'especialidades',
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
    ]
