# Generated by Django 5.1.5 on 2026-07-21 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorperfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disponibilidadhoraria',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='doctores.doctorperfil'),
        ),
        migrations.AddField(
            model_name='bloqueohorario',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='doctores.doctorperfil'),
        ),
        migrations.AddField(
            model_name='doctorperfil',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctores', to='doctores.especialidad'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadhoraria',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fin__gt', models.F('hora_inicio'))), name='disponibilidad_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadhoraria',
            constraint=models.UniqueConstraint(fields=('doctor', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uq_disponibilidad_doctor_bloque'),
        ),
        migrations.AddIndex(
            model_name='bloqueohorario',
            index=models.Index(fields=['doctor', 'fecha_inicio', 'fecha_fin'], name='idx_bloqueo_doctor_rango'),
        ),
        migrations.AddConstraint(
            model_name='bloqueohorario',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='bloqueo_rango_valido'),
        ),
    ]
