# Generated by Django 5.1.5 on 2026-07-21 20:55

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='archivos_medicos/%Y/%m/')),
                ('nombre', models.CharField(max_length=180)),
                ('tipo', models.CharField(choices=[('examen', 'Examen de laboratorio'), ('imagen', 'Imagenologia'), ('informe', 'Informe medico'), ('otro', 'Otro')], default='otro', max_length=20)),
            ],
            options={
                'verbose_name': 'Archivo medico',
                'verbose_name_plural': 'Archivos medicos',
                'db_table': 'archivos_medicos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alergias', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('enfermedades_cronicas', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('medicamentos_actuales', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('antecedentes_familiares', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
            ],
            options={
                'verbose_name': 'Historial medico',
                'verbose_name_plural': 'Historiales medicos',
                'db_table': 'historiales_medicos',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicamento', models.CharField(max_length=180)),
                ('dosis', models.CharField(max_length=120)),
                ('frecuencia', models.CharField(max_length=120)),
                ('duracion', models.CharField(max_length=120)),
                ('indicaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'db_table': 'recetas',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostico', apps.core.fields.TextoCifradoField()),
                ('tratamiento', apps.core.fields.TextoCifradoField(blank=True, default='')),
                ('notas', apps.core.fields.TextoCifradoField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Registro de consulta',
                'verbose_name_plural': 'Registros de consulta',
                'db_table': 'registros_consulta',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
