# Generated by Django 5.1.5 on 2026-07-21 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
        ('historiales', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialmedico',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pacientes.pacienteperfil'),
        ),
        migrations.AddField(
            model_name='registroconsulta',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registro_consulta', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='registroconsulta',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='historiales.historialmedico'),
        ),
        migrations.AddField(
            model_name='receta',
            name='registro_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='historiales.registroconsulta'),
        ),
        migrations.AddField(
            model_name='archivomedico',
            name='registro_consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='historiales.registroconsulta'),
        ),
        migrations.AddIndex(
            model_name='registroconsulta',
            index=models.Index(fields=['historial', '-created_at'], name='idx_registro_historial'),
        ),
    ]
