# Generated by Django 5.1.5 on 2026-07-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('lectura', 'Lectura'), ('escritura', 'Escritura'), ('exportacion', 'Exportacion'), ('eliminacion', 'Eliminacion')], db_index=True, max_length=20)),
                ('modelo_afectado', models.CharField(db_index=True, max_length=80)),
                ('objeto_id', models.CharField(blank=True, max_length=64)),
                ('ruta', models.CharField(blank=True, max_length=255)),
                ('metodo', models.CharField(blank=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Acceso auditado',
                'verbose_name_plural': 'Accesos auditados',
                'db_table': 'auditoria_acceso',
                'ordering': ['-fecha'],
            },
        ),
    ]
